version: 2.1

executors:
  integration_executor:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      PYENV_VERSION: 3.7.0

commands:
  integration_test:
    description: Reproducing issue
    steps:
      - run:
          name: apt update
          command: |
              wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
              wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
              sudo apt update
              sudo apt install -y libmysqlclient-dev

jobs: 
  run_integration_test:
    executor: integration_executor
    steps:
      - integration_test

workflows:
  version: 2
  build_and_test:
    jobs:
      - run_integration_test
